version: '3.8'
services:
  web:
    image: php:8.2-apache
    volumes:
      - ..:/var/www/html
    ports:
      - "8080:80"
    command: >
      sh -c "docker-php-ext-install mysqli &&
      chown -R www-data:www-data /var/www/html &&
      apache2-foreground"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: teddy_db
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: PASSWORD
    volumes:
      - ./phpmyadmin-config.php:/etc/phpmyadmin/config.user.inc.php
